stages:
- test
- build
- kill
- deploy

testing:
  stage: test
  script:
    - echo testing

.preamble: &preamble
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r test/requirements.txt

sanity-test:
  stage: test
  script:
    - *preamble
    - pytest test/test_sanity.py

# Tests of the support test code which should be executed
# before other bot-related tests
bot-resp-test:
  stage: test
  script:
    - *preamble
    - pytest test/bots/test_bot_resp.py

bot-entry-test:
  stage: test
  script:
    - *preamble
    - pytest test/bots/test_bot_entry.py



# The following are done only on master branch.

docker-build:
  stage: build
  script:
    - docker build -t sexp  .
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

docker-prune-images:
  stage: build
  script:
    - docker image prune
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

docker-kill-prev-container:
  stage: kill
  script:
    - docker stop sexp-container
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
  allow_failure: true

docker-deploy:
  stage: deploy
  script:
    - docker run --rm --name sexp-container -d -p5000:5000 sexp
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

aws-login:
  stage: deploy
  script:
    - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 105339933835.dkr.ecr.eu-west-2.amazonaws.com
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

aws-tag:
  stage: deploy
  script:
    - docker tag sexp 105339933835.dkr.ecr.eu-west-2.amazonaws.com/sexp:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

aws-push:
  stage: deploy
  needs: ["aws-login", "aws-tag"]
  script:
    - docker push 105339933835.dkr.ecr.eu-west-2.amazonaws.com/sexp:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "master"