stages:
- test
- build
- kill
- deploy

testing:
  stage: test
  script:
    - echo testing

.preamble: &preamble
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r test/requirements.txt
  - pip install -r flaskr/requirements.txt

sanity-test:
  stage: test
  script:
    - *preamble
    - pytest test/test_sanity.py

# Tests of the support test code which should be executed
# before other bot-related tests
bot-resp-test:
  stage: test
  script:
    - *preamble
    - pytest test/bots/test_bot_resp.py

bot-entry-test:
  stage: test
  script:
    - *preamble
    - pytest test/bots/test_bot_entry.py

flaskr-test:
  stage: test
  script:
    - *preamble
    - pytest tests/test_flaskr.py



# The following are done only on master branch.

docker-build-image:
  stage: build
  script:
    - docker build -t se-xp  .
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

docker-clear-old-resources:
  stage: kill
  script:
    - docker system prune --filter "until=24h" --force
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

docker-stop-previous-container:
  stage: kill
  script:
    - docker stop se-xp-container
  rules:
  - if: $CI_COMMIT_BRANCH == "master"

dockerremove-previous-container:
  stage: kill
  script:
    - docker rm se-xp-container
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
  allow_failure: true

docker-run-new-container:
  stage: deploy
  script:
    - docker run --name se-xp-container -d -p80:5000 se-xp
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

fly-deploy:
  stage: deploy
  script:
    - /home/gitlab-runner/.fly/bin/fly deploy . --detach --now
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
